name: 📱 Android
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-android
  cancel-in-progress: true

jobs:
  android:
    name: Android
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        lib-type: ${{ github.event_name == 'pull_request' && fromJSON('["static"]') || fromJSON('["static", "shared"]') }}
        build-type: ${{ github.event_name == 'pull_request' && fromJSON('["Release"]') || fromJSON('["Release", "Debug"]') }}
    env:
      URHO3D_LIB_TYPE: ${{ matrix.lib-type == 'shared' && 'SHARED' || 'STATIC' }}
      CMAKE_BUILD_TYPE: ${{ matrix.build-type }}
      GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Library
        run: ./gradlew :android:urho3d-lib:externalNativeBuild${{ matrix.build-type }}

      - name: Assemble Library
        run: ./gradlew :android:urho3d-lib:assemble${{ matrix.build-type }}

      - name: Build Launcher (shared only)
        if: matrix.lib-type == 'shared'
        run: ./gradlew :android:launcher-app:externalNativeBuild${{ matrix.build-type }} :android:launcher-app:assemble${{ matrix.build-type }}

      - name: Test
        run: ./gradlew :android:urho3d-lib:test

      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        run: ./gradlew publish
