name: 📖 Documentation
on:
  push:
    branches:
      - master
      - 'releases/**'
  workflow_dispatch: ~

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-docs
  cancel-in-progress: true

env:
  CCACHE_DIR: ${{ github.workspace }}/.ccache

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: linux-static-Release-${{ github.sha }}
          restore-keys: |
            linux-static-Release-

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential ccache pkg-config doxygen graphviz \
            libgl1-mesa-dev libglew-dev \
            libxcursor-dev libxext-dev libxi-dev libxinerama-dev libxrandr-dev libxrender-dev libxss-dev libxxf86vm-dev \
            libwayland-dev libxkbcommon-dev wayland-protocols \
            libasound2-dev libpulse-dev \
            libibus-1.0-dev \
            libdbus-1-dev libreadline6-dev libssl-dev libudev-dev uuid-dev

      - name: CMake
        run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DURHO3D_LIB_TYPE=static -DURHO3D_DOCS=1 -DURHO3D_PLAYER=0 -DURHO3D_PROFILING=0 -DURHO3D_SAMPLES=0 -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build build --parallel 2 --target all --config Release -- -j2

      - name: Build Documentation
        run: cmake --build build --target doc
