name: 📖 Documentation
on:
  push:
    branches:
      - master
      - 'releases/**'
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CCACHE_DIR: ${{ github.workspace }}/.ccache

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: docs-${{ github.sha }}
          restore-keys: |
            docs-

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential ccache pkg-config doxygen graphviz \
            libgl1-mesa-dev libglew-dev \
            libxcursor-dev libxext-dev libxi-dev libxinerama-dev libxrandr-dev libxrender-dev libxss-dev libxxf86vm-dev \
            libwayland-dev libxkbcommon-dev wayland-protocols \
            libasound2-dev libpulse-dev \
            libibus-1.0-dev \
            libdbus-1-dev libreadline6-dev libssl-dev libudev-dev uuid-dev

      - name: CMake
        run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DURHO3D_LIB_TYPE=static -DURHO3D_DEPLOYMENT_TARGET=generic -DURHO3D_DOCS=1 -DURHO3D_PLAYER=0 -DURHO3D_PROFILING=0 -DURHO3D_SAMPLES=0 -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build build --parallel $(nproc) --target all --config Release

      - name: Build Documentation
        run: cmake --build build --target doc
