name: 🐧 Linux
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-linux
  cancel-in-progress: true

env:
  CCACHE_DIR: ${{ github.workspace }}/.ccache

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lib-type: ${{ github.event_name == 'pull_request' && fromJSON('["static"]') || fromJSON('["static", "shared"]') }}
        build-type: ${{ github.event_name == 'pull_request' && fromJSON('["Release"]') || fromJSON('["Release", "Debug"]') }}
        compiler: ${{ github.event_name == 'pull_request' && fromJSON('["gcc"]') || fromJSON('["gcc", "clang"]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ github.job }}-${{ matrix.compiler }}-${{ matrix.lib-type }}-${{ matrix.build-type }}-${{ github.sha }}
          restore-keys: |
            ${{ github.job }}-${{ matrix.compiler }}-${{ matrix.lib-type }}-${{ matrix.build-type }}-

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential ccache ninja-build pkg-config \
            libgl1-mesa-dev libglew-dev \
            libxcursor-dev libxext-dev libxi-dev libxinerama-dev libxrandr-dev libxrender-dev libxss-dev libxxf86vm-dev \
            libwayland-dev libxkbcommon-dev wayland-protocols \
            libasound2-dev libpulse-dev \
            libibus-1.0-dev \
            libdbus-1-dev libreadline6-dev libssl-dev libudev-dev uuid-dev
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            sudo apt-get install -y --no-install-recommends clang
          fi

      - name: CMake
        run: |
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            export CC=clang
            export CXX=clang++
          fi
          cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DURHO3D_LIB_TYPE=${{ matrix.lib-type }} -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DURHO3D_DEPLOYMENT_TARGET=generic

      - name: Build
        run: cmake --build build --parallel 2 --target all --config ${{ matrix.build-type }} -- -j2

      - name: Test
        run: ctest --test-dir build --output-on-failure -C ${{ matrix.build-type }}

      - name: Package
        #if: startsWith(github.ref, 'refs/tags/')
        run: cmake --build build --target package --config ${{ matrix.build-type }}

      - name: Upload packages
        #if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: 'U3D-${{ github.job }}-${{ matrix.compiler }}-${{ matrix.lib-type }}-${{ matrix.build-type }}'
          path: build/*.tar.gz
