name: 💻 MacOS
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: true

jobs:
  macOS:
    name: MacOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        lib-type: ${{ github.event_name == 'pull_request' && fromJSON('["static"]') || fromJSON('["static", "shared"]') }}
        build-type: ${{ github.event_name == 'pull_request' && fromJSON('["Release"]') || fromJSON('["Release", "Debug"]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: CMake
        run: cmake -S . -B build -G Xcode -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DURHO3D_LIB_TYPE=${{ matrix.lib-type }} -DTRACY_NO_PARALLEL_ALGORITHMS=ON -DURHO3D_DEPLOYMENT_TARGET=generic -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13

      - name: Build
        run: cmake --build build --config ${{ matrix.build-type }}

      - name: Test
        run: ctest --test-dir build --output-on-failure -C ${{ matrix.build-type }}

      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        run: cmake --build build --target package --config ${{ matrix.build-type }}

      - name: Upload packages
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: 'U3D-${{ github.job }}-${{ matrix.lib-type }}-${{ matrix.build-type }}-${{ github.sha }}'
          path: build/*.tar.gz
