name: 🌎 Web
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-web
  cancel-in-progress: true

jobs:
  web:
    name: Web
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - Release
          - Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential ninja-build

      - name: Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.60

      - name: Verify Emscripten
        run: emcc -v

      - name: CMake
        run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DURHO3D_LIB_TYPE=static -DEMSCRIPTEN_SHARE_DATA=1 -DWEB=1 -DURHO3D_PROFILING=0

      - name: Build
        run: cmake --build build --parallel 2 --config ${{ matrix.build-type }}
