name: 🌎 Web
on:
  push:
    branches:
      - master
      - 'releases/**'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
      - 'Docs/**'
      - 'website/**'
      - 'LICENSE'
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web:
    name: Web
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - Release
          - Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential ninja-build

      - name: Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.60
          actions-cache-folder: 'emsdk-cache-${{ matrix.build-type }}'

      - name: Verify Emscripten
        run: emcc -v

      - name: CMake
        run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DURHO3D_LIB_TYPE=static -DEMSCRIPTEN_SHARE_DATA=1 -DWEB=1 -DURHO3D_PROFILING=0

      - name: Build
        run: cmake --build build --parallel $(nproc) --config ${{ matrix.build-type }}
